"""add join code to projects

Revision ID: d521cd7ea915
Revises: 739dca998ec8
Create Date: 2026-05-18 18:07:56.987084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd521cd7ea915'
down_revision: Union[str, Sequence[str], None] = '739dca998ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('projects', sa.Column('join_code', sa.String(), nullable=True))
    op.execute("""
        UPDATE projects SET join_code = upper(
            substr(replace(replace(replace(gen_random_uuid()::text, '-', ''), 'o', 'X'), '0', 'Z'), 1, 6)
        )
    """)
    op.create_index(op.f('ix_projects_join_code'), 'projects', ['join_code'], unique=True)
    op.alter_column('projects', 'join_code', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_join_code'), table_name='projects')
    op.drop_column('projects', 'join_code')
    # ### end Alembic commands ###
