"""use enum for repository status

Revision ID: f864eed4a752
Revises: 94992c37d3b8
Create Date: 2026-05-11 20:16:01.833455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f864eed4a752'
down_revision: Union[str, Sequence[str], None] = '94992c37d3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    repositorystatus = sa.Enum('LINKED', 'ANALYZING', 'ANALYZED', 'FAILED', name='repositorystatus')
    repositorystatus.create(op.get_bind())

    op.execute("ALTER TABLE repositories ALTER COLUMN status TYPE repositorystatus USING status::repositorystatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'status',
               existing_type=sa.Enum('LINKED', 'ANALYZING', 'ANALYZED', 'FAILED', name='repositorystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    repositorystatus = sa.Enum('LINKED', 'ANALYZING', 'ANALYZED', 'FAILED', name='repositorystatus')
    repositorystatus.drop(op.get_bind())
    # ### end Alembic commands ###
